### ISSUE TITLE
System.AccessViolationException with Windows 11 24H2

### ISSUE THREAD

**Issue by Dave-1337** [LittleVaaty/VDesk#22]
Hello, is it possible that the current Beta5 is not compatible with Windows 11 24H2? I have installed a current .Net Runtime 8.08 in 32Bit and 64Bit, but VDESK cannot create virtual desktops, the error code always appears:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at <VDesk_Interop_Build22631_3155_IVirtualDesktopManagerInternal>FCDB919E5438FED29D6A5DB9FDFA5A4D8B66FE673DD75E14D8A0DAA870FDB2A8C__InterfaceImplementation.global::VDesk.Interop.Build22631_3155.IVirtualDesktopManagerInternal.CreateDesktop()
   at VDesk.Interop.Build22631_3155.VirtualDesktopProvider.CreateDesktop()
   at VDesk.Commands.CreateCommand.Execute(McMaster.Extensions.CommandLineUtils.CommandLineApplication)
   at VDesk.Commands.VdeskCommandBase.OnExecute(McMaster.Extensions.CommandLineUtils.CommandLineApplication)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Object, System.Span`1<System.Object>, System.Reflection.BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(System.Reflection.MethodInfo, System.Object, System.Object[])
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<OnExecute>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<OnExecute>d__1, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<OnExecute>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<OnExecute>d__1, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<OnExecute>d__1 ByRef)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(McMaster.Extensions.CommandLineUtils.Conventions.ConventionContext, System.Threading.CancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<>c__DisplayClass0_0+<<Apply>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<>c__DisplayClass0_0+<<Apply>b__0>d, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<<Apply>b__0>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<>c__DisplayClass0_0+<<Apply>b__0>d, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<<Apply>b__0>d ByRef)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention+<>c__DisplayClass0_0.<Apply>b__0(System.Threading.CancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication+<ExecuteAsync>d__154.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[McMaster.Extensions.CommandLineUtils.CommandLineApplication+<ExecuteAsync>d__154, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<ExecuteAsync>d__154 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[McMaster.Extensions.CommandLineUtils.CommandLineApplication+<ExecuteAsync>d__154, McMaster.Extensions.CommandLineUtils, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<ExecuteAsync>d__154 ByRef)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(System.String[], System.Threading.CancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1+<RunAsync>d__4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1+<RunAsync>d__4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunAsync>d__4<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1+<RunAsync>d__4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunAsync>d__4<System.__Canon> ByRef)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync(System.Threading.CancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime+<>c__DisplayClass10_0+<<WaitForStartAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime+<>c__DisplayClass10_0+<<WaitForStartAsync>b__0>d, McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<<WaitForStartAsync>b__0>d ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime+<>c__DisplayClass10_0+<<WaitForStartAsync>b__0>d, McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<<WaitForStartAsync>b__0>d ByRef)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime+<>c__DisplayClass10_0.<WaitForStartAsync>b__0()
   at System.Threading.CancellationTokenSource.Invoke(System.Delegate, System.Object, System.Threading.CancellationTokenSource)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(System.Threading.CancellationTokenSource)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__15, Microsoft.Extensions.Hosting, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__15 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__15, Microsoft.Extensions.Hosting, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__15 ByRef)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.HostExtensions+<RunCommandLineApplicationAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostExtensions+<RunCommandLineApplicationAsync>d__0, McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.Extensions.Hosting.HostExtensions+<RunCommandLineApplicationAsync>d__0, McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__0 ByRef)
   at Microsoft.Extensions.Hosting.HostExtensions.RunCommandLineApplicationAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__1`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__1`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__1`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__1`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__1`1<System.__Canon> ByRef)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.Extensions.Hosting.IHostBuilder, System.String[], System.Action`1<McMaster.Extensions.CommandLineUtils.CommandLineApplication`1<System.__Canon>>, System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__0`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.Extensions.Hosting.HostBuilderExtensions+<RunCommandLineApplicationAsync>d__0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], McMaster.Extensions.Hosting.CommandLine, Version=4.1.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d]](<RunCommandLineApplicationAsync>d__0`1<System.__Canon> ByRef)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.Extensions.Hosting.IHostBuilder, System.String[], System.Threading.CancellationToken)
   at VDesk.VDesk+<MainAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[VDesk.VDesk+<MainAsync>d__1, VDesk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<MainAsync>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[VDesk.VDesk+<MainAsync>d__1, VDesk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<MainAsync>d__1 ByRef)
   at VDesk.VDesk.MainAsync(System.String[])
   at VDesk.VDesk.Main(System.String[])


```

**Comment by LittleVaaty** [comment]
Yes, i think the last update of windows 11 break vdesk
Saddly since vdesk use an undocumented api of windows, this append a lot :/

**Comment by Dave-1337** [comment]
Do you still see any possibilities to get VDESK functional again, or will 24H2 mean the end for vDesk? :-/

**Comment by Dave-1337** [comment]
Windows 11 24h2 has now been officially released. Do you perhaps already have a workaround how to get VDesk running again?

**Comment by saphtea** [comment]
Hey! Hopin to see progress on this, using vdesk to automate my art workflows in various desktops on login, would love to use what I was using in W10 :)

**Comment by LittleVaaty** [comment]
I'm working on it, hope to push it by the end of the week.

**Comment by LittleVaaty** [comment]
The beta 5 should fix the problem
